server:
  port: 8080
  servlet:
    context-path: /jwt3

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/spring_boot3_jwt'
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  application:
#    name: '/jwt3'

jwt:
  signerKey: cThl2O+Ogi/nkciMZpyIlXw6l4Zsh7dyUZfExYssEJaegAmbsInT6dUVR5n9pjA9

