server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/hibernate_n1_problem"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
