server:
  port: 8080
#  servlet:
#    context-path: '/mapstruct'

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/data_mapper'
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
